{
 "title": "vaccinations_dashboard",
 "time": { "from": "2020-12-13T00:00:00.000Z", "to": "2021-02-24T00:00:00.000Z" },
 "panels": [
  {
   "title": "Vaccinations journalières en Europe Occidentale depuis Décembre 2020",
   "type": "graph",
   "gridPos": { "h": 8, "w": 13, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  date AS \"time\",\n  country AS metric,\n  daily_vaccinations\nFROM data\nWHERE\n  country = 'France'\nORDER BY date"
    },
    {
     "rawSql": "SELECT\n  date AS \"time\",\n  country AS metric,\n  daily_vaccinations\nFROM data\nWHERE\n  country = 'Belgium'\nORDER BY date"
    },
    {
     "rawSql": "SELECT\n  date AS \"time\",\n  country AS metric,\n  daily_vaccinations\nFROM data\nWHERE\n  country = 'Denmark'\nORDER BY date"
    },
    {
     "rawSql": "SELECT\n  date AS \"time\",\n  country AS metric,\n  daily_vaccinations\nFROM data\nWHERE\n  country = 'England'\nORDER BY date"
    },
    {
     "rawSql": "SELECT\n  date AS \"time\",\n  country AS metric,\n  daily_vaccinations\nFROM data\nWHERE\n  country = 'Finland'\nORDER BY date"
    },
    {
     "rawSql": "SELECT\n  date AS \"time\",\n  country AS metric,\n  daily_vaccinations\nFROM data\nWHERE\n  country = 'Germany'\nORDER BY date"
    },
    {
     "rawSql": "SELECT\n  date AS \"time\",\n  country AS metric,\n  daily_vaccinations\nFROM data\nWHERE\n  country = 'Italy'\nORDER BY date"
    },
    {
     "rawSql": "SELECT\n  date AS \"time\",\n  country AS metric,\n  daily_vaccinations\nFROM data\nWHERE\n  country = 'Switzerland'\nORDER BY date"
    }
   ]
  },
  {
   "title": "Pourcentage de personnes vaccinés en Europe Occidentale depuis Décembre 2020",
   "type": "bargauge",
   "gridPos": { "h": 12, "w": 11, "x": 13, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  date AS \"time\",\n  country AS metric,\n  people_vaccinated_per_hundred\nFROM data\nWHERE\n  country = 'France'\nORDER BY date"
    },
    {
     "rawSql": "SELECT\n  date AS \"time\",\n  country AS metric,\n  people_vaccinated_per_hundred\nFROM data\nWHERE\n  country = 'England'\nORDER BY date"
    },
    {
     "rawSql": "SELECT\n  date AS \"time\",\n  country AS metric,\n  people_vaccinated_per_hundred\nFROM data\nWHERE\n  country = 'Belgium'\nORDER BY date"
    },
    {
     "rawSql": "SELECT\n  date AS \"time\",\n  country AS metric,\n  people_vaccinated_per_hundred\nFROM data\nWHERE\n  country = 'Denmark'\nORDER BY date"
    },
    {
     "rawSql": "SELECT\n  date AS \"time\",\n  country AS metric,\n  people_vaccinated_per_hundred\nFROM data\nWHERE\n  country = 'Finland'\nORDER BY date"
    },
    {
     "rawSql": "SELECT\n  date AS \"time\",\n  country AS metric,\n  people_vaccinated_per_hundred\nFROM data\nWHERE\n  country = 'Italy'\nORDER BY date"
    },
    {
     "rawSql": "SELECT\n  date AS \"time\",\n  country AS metric,\n  people_vaccinated_per_hundred\nFROM data\nWHERE\n  country = 'Germany'\nORDER BY date"
    },
    {
     "rawSql": "SELECT\n  date AS \"time\",\n  country AS metric,\n  people_vaccinated_per_hundred\nFROM data\nWHERE\n  country = 'Switzerland'\nORDER BY date"
    },
    {
     "rawSql": "SELECT\n  date AS \"time\",\n  country AS metric,\n  people_vaccinated_per_hundred\nFROM data\nWHERE\n  country = 'Spain'\nORDER BY date"
    }
   ]
  },
  {
   "title": "Vaccinations en Europe Occidentale depuis Décembre 2020",
   "type": "graph",
   "gridPos": { "h": 10, "w": 13, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  date AS \"time\",\n  country AS metric,\n  total_vaccinations AS \"total_vaccinations\"\nFROM data\nWHERE\n  country = 'France'\nORDER BY date"
    },
    {
     "rawSql": "SELECT\n  date AS \"time\",\n  country AS metric,\n  total_vaccinations\nFROM data\nWHERE\n  country = 'England'\nORDER BY date"
    },
    {
     "rawSql": "SELECT\n  date AS \"time\",\n  country AS metric,\n  total_vaccinations\nFROM data\nWHERE\n  country = 'Spain'\nORDER BY date"
    },
    {
     "rawSql": "SELECT\n  date AS \"time\",\n  country AS metric,\n  total_vaccinations\nFROM data\nWHERE\n  country = 'Germany'\nORDER BY date"
    },
    {
     "rawSql": "SELECT\n  date AS \"time\",\n  country AS metric,\n  total_vaccinations\nFROM data\nWHERE\n  country = 'Italy'\nORDER BY date"
    },
    {
     "rawSql": "SELECT\n  date AS \"time\",\n  country AS metric,\n  total_vaccinations\nFROM data\nWHERE\n  country = 'Switzerland'\nORDER BY date"
    },
    {
     "rawSql": "SELECT\n  date AS \"time\",\n  country AS metric,\n  total_vaccinations\nFROM data\nWHERE\n  country = 'Denmark'\nORDER BY date"
    },
    {
     "rawSql": "SELECT\n  date AS \"time\",\n  country AS metric,\n  total_vaccinations\nFROM data\nWHERE\n  country = 'Belgium'\nORDER BY date"
    }
   ]
  }
 ]
}