apiVersion: 1

datasources:
  - name: mysql-container
    type: mysql
    access: proxy
    url: mysql:3306
    password: eureden
    user: root
    database: vaccinations
    isDefault: True